name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - main

jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout the repository
      uses: actions/checkout@main
    - name: Installing the dependencies
      run: npm install
    - name: Building the production code
      run: npm run build
    - name: Deploy to Firebase
      uses: w9jds/firebasae-action@main
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}